### ISSUE TITLE
Still no source code

### ISSUE THREAD

**Issue by GReaperEx** [deltaray/num-utils#1]
So many years have passed, but you have yet to release any source code on this "num-utils". What gives? Others may want to continue and/or improve your code, expand it etc. You're holding this project way back by hiding the source...

**Comment by deltaray** [comment]
Hi. Thanks for using num-utils.  I'm confused as the source code is right here in this github repo. Are you referring to something else?  Its not my intent to hide any source code.

**Comment by GReaperEx** [comment]
Well, this is embarrassing... Sorry for saying that without checking the source here, I had a bad week fiddling with CLI Ubuntu and being sleepless.

Please forget I ever wrote that. :)

**Comment by deltaray** [comment]
Heh, no worries it happens. Did you remember if you had any problem specifically with num-utils?  I've encountered a few bugs in the programs and I think its about time I fix them, but I can't remember now what they are.

**Comment by GReaperEx** [comment]
Well, two problems I had with them and wanted to fix, were that you can only input 1 number per line and that the program can accept only a single file. I don't know though if that is still true, I may have been using a really old version. Downloaded it from here:
http://suso.suso.org/programs/num-utils/
